### ISSUE TITLE
changeo_assign_genes and changeo_assign_genes_reveal are almost identical, try to use one

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/bcellmagic#2]
Hi @ggabernet `changeo_assign_genes.nf` and `changeo_assign_genes_reveal.nf` are almost identical. When we have standardized `meta` to connect bcellmagic and reveal, I think we will be able to just have `changeo_assign_genes.nf`. The only differences are the use of ` label immcantation` and that `changeo_assign_genes_reveal.nf` takes the values for `organism` and `loci` from `meta`, whereas the original `changeo_assign_genes.nf` uses `params`.

**Comment by ggabernet** [comment]
yes, that sounds great @ssnn-airr
